get_world_offset = """
return vec2f(0., 0.);
"""

get_fragment_color = """
return textureSample(scene_color_texture, sampler_scene_color_texture, uv0.xy) * vec4f(2.0, 0.0, 0.3, 1.0);
"""

[texture_descs]
scene_color_texture = "linear"
